import type { InferGetStaticPropsType, NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Link from "next/link";
import { getSortedPostsData } from "../lib/posts";
import { GetStaticProps } from "next";
import Date from "../components/date";

interface Metadata {
  id: string;
  title: string;
  date: string;
}

type Posts = Metadata[];

const Home: NextPage = ({
  allPostsData,
}: InferGetStaticPropsType<typeof getStaticProps>) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js! Keepo</a>
        </h1>

        <h1 className="text-4xl mb-4 p-4 font-extrabold text-transparent bg-clip-text bg-gradient-to-r from-purple-400 to-pink-600">
          Heylo
        </h1>

        <section className="">
          <h2 className="text-2xl mt-4">Blog</h2>
          <ul className="mt-2">
            {allPostsData.map(({ id, date, title }: Metadata) => (
              <li className="mb-2" key={id}>
                <Link href={`posts/${id}`}>
                  <a className="text-blue-700 hover:underline"> {title} </a>
                </Link>
                <br />
                <Date dateString={date} /> <br />
              </li>
            ))}
          </ul>
        </section>

        <Link href="posts/first-post">
          <a className="mt-4"> Go To Page</a>
        </Link>
      </main>
    </div>
  );
};

export default Home;

export const getStaticProps: GetStaticProps = () => {
  const allPostsData: Posts = getSortedPostsData();
  return {
    props: {
      allPostsData,
    },
  };
};
